apiVersion: v1
kind: Service
metadata:
  name: mongo-db-service
  labels:
    apps: mongo-db-service
spec:
  type: NodePort
  ports:
  - name: tcp-31081-5000
    nodePort: 31081
    port: 27017
    protocol: TCP
  selector:
    app: mongo-db
