apiVersion: v1
kind: Service
metadata:
  name: mongo-express-service
  labels:
    apps: mongo-express-service
spec:
  type: NodePort
  ports:
  - name: tcp-31081-5000
    nodePort: 31082
    port: 8081
    protocol: TCP
  selector:
    app: mongo-express
