//Maninly used for storing sensitive data

apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
data:
  DB_host: mysql
  DB_user: xxxyxyxxxx         //encrypted
  DB_password: xxyyxyyxyx    //encrypted



// To encrypt the data use the command

echo -n 'mysql' | base64


// To decode

echo -n 'xxxxx' | base64 --decode
